### ISSUE TITLE
TypeError: e.field.onChange is not a function

### ISSUE THREAD

**Issue by gziolo** [Automattic/delphin#1142]
https://sentry.io/automattic-1o/delphin/issues/170717824/

```
TypeError: e.field.onChange is not a function
  at n.onClickGridicon (/wp-content/themes/a8c/getdotblog/public/scripts/bundle.489b2f1c61fbf4475445.js:1:124866)
  at Object.r (/wp-content/themes/a8c/getdotblog/public/scripts/vendor.489b2f1c61fbf4475445.js:1:117605)
  at i (/wp-content/themes/a8c/getdotblog/public/scripts/vendor.489b2f1c61fbf4475445.js:1:90326)
  at Object.c [as executeDispatchesInOrder] (/wp-content/themes/a8c/getdotblog/public/scripts/vendor.489b2f1c61fbf4475445.js:1:90541)
  at p (/wp-content/themes/a8c/getdotblog/public/scripts/vendor.489b2f1c61fbf4475445.js:1:77851)
...
(11 additional frame(s) were not displayed)
```

Browser: Mobile Chrome.

If I read minified code properly, this error is triggered around this place: https://github.com/Automattic/delphin/blob/master/app/components/ui/form/input.js#L74.

**Comment by gziolo** [comment]
Project is no longer developed so closing this one.
